import assert from 'node:assert/strict';
import test from 'node:test';

import { getSessionDisplayName } from '../src/pages/chat/session-display-name.ts';

function makeSession(name: string, createdAt: string) {
	return {
		id: 'session-1',
		created_at: createdAt,
		config: { name },
	};
}

test('converts generated UTC session names to the display timezone', () => {
	const session = makeSession('2026-07-28 01:00:00', '2026-07-28T01:00:00.250000');

	assert.equal(
		getSessionDisplayName(session, 'Asia/Shanghai'),
		'2026-07-28 09:00:00',
	);
});

test('keeps timezone-aware scheduler names generated by the new backend', () => {
	const session = makeSession('2026-07-28 09:00:00', '2026-07-28T01:00:00.250000');

	assert.equal(
		getSessionDisplayName(session, 'Asia/Shanghai'),
		'2026-07-28 09:00:00',
	);
});

test('keeps manually renamed sessions unchanged', () => {
	assert.equal(
		getSessionDisplayName(makeSession('daily report', '2026-07-28T01:00:00'), 'Asia/Shanghai'),
		'daily report',
	);
});

test('falls back to the session id when the name is empty', () => {
	assert.equal(
		getSessionDisplayName(makeSession('', '2026-07-28T01:00:00'), 'Asia/Shanghai'),
		'session-1',
	);
});
